# Generated by Django 5.2.3 on 2025-06-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Student Name')),
                ('roll', models.IntegerField(unique=True)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
    ]
