# Generated by Django 5.2.3 on 2025-06-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_father_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
