CREATE TABLE Employee (
    EmpID INT NOT NULL PRIMARY KEY,
    EmpName VARCHAR(50) NOT NULL,
    Gender VARCHAR(10) NOT NULL
);

CREATE TABLE EmployeeDetails (
    EmpID INT NOT NULL PRIMARY KEY,
    Designation VARCHAR(50) NULL,
    Department VARCHAR(50) NULL,
    JoiningDate DATETIME NULL,
    FOREIGN KEY (EmpID) REFERENCES Employee(EmpID) ON DELETE CASCADE
);



CREATE TABLE FieldOfWork (
    EmpID INT NOT NULL PRIMARY KEY,
    WorkField VARCHAR(50) NOT NULL,
    FOREIGN KEY (EmpID) REFERENCES Employee(EmpID) ON DELETE CASCADE
);

CREATE TABLE WorkingHours (
    EmpID INT NOT NULL PRIMARY KEY,
    HoursPerDay DECIMAL(4, 2) NOT NULL,
    ShiftType VARCHAR(20) NOT NULL,
    FOREIGN KEY (EmpID) REFERENCES Employee(EmpID) ON DELETE CASCADE
);

CREATE TABLE EmployeeExpertise (
    ExpertiseID INT AUTO_INCREMENT PRIMARY KEY,
    EmpID INT NOT NULL,
    ExpertiseArea VARCHAR(50) NOT NULL,
    FOREIGN KEY (EmpID) REFERENCES Employee(EmpID) ON DELETE CASCADE
);

CREATE TABLE SalaryInfo (
    EmpID INT NOT NULL PRIMARY KEY,
    BasicSalary DECIMAL(10, 2) NOT NULL,
    Allowances DECIMAL(10, 2) DEFAULT 0.00,
    TotalSalary DECIMAL(10, 2) GENERATED ALWAYS AS (BasicSalary + Allowances) STORED,
    FOREIGN KEY (EmpID) REFERENCES Employee(EmpID) ON DELETE CASCADE
);
