# Generated by Django 5.2.3 on 2025-06-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='student/photos/'),
        ),
    ]
